project:
  type: website
  output-dir: docs

website:
  title: "Erin Hulland Frame"
  site-url: "https://ehulland.github.io/"
  repo-url: "https://github.com/ehulland/ehulland.github.io"
  
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About Me"
        href: about.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Talks and Presentations"
        href: talks.qmd
      - text: "Timeline Map"
        href: talkmap/map.html
      - text: "Posts"
        href: posts.qmd
      - text: "CV"
        href: cv.qmd

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    toc: false

execute:
  freeze: auto
