---
title: "Curriculum Vitae"
---

Education
======
* B.S. in Biology and French, Statistics Minor, Pennsylvania State University, 2012
* MPH in Biostatistics, Emory University Rollins School of Public Health, 2014
* PhD in Global Health - Metrics Track, University of Washington, 2023

Relevant work experience
======
* 10/2025 - present
	* Department of Viroscience, Erasmus MC, Rotterdam, Netherlands
		* Postdoctoral Researcher: 10/2025 - present
* 10/2023 - 10/2025
	* Computational Health Informatics Program, Boston Children's Hospital & Harvard Medical School, Boston, MA
		* Postdoctoral Research Consultant, Majumder Lab: 10/2023-10/2025

* 09/2018 - 09/2023
	* Institute for Health Metrics and Evaluation, Seattle WA
		* Researcher, Pandemics Team: 01/2023 - present
		* Researcher, COVID-19 Pandemics Team: 09/2020 - 12/2022
		* Pre-doctoral researcher, Local Burden of Disease Pandemics Team: 09/2018 - 09/2020

* 06/2020 - 09/2020
	* Bill and Melinda Gates Foundation, Seattle WA
		* Summer Associate, Global Development Division, Polio Eradication Team

* 06/2014 - 07/2018
	* U.S. Centers for Disease Control and Prevention, Atlanta GA
		* Biostatistician - Center for Global Health, Emergency Response and Recovery Branch: 04/2016 - 07/2018
		* Junior Biostatistician (ORISE Fellow) - Center for Global Health, Emergency Response and Recovery Branch: 06/2014 - 04/2016
* 11/2013 - 05/2014
	* American Cancer Society, Atlanta GA
		* Intern - Surveillance and Healthy Services Research Team

Skills
======
* Languages
	* English (Native tongue)
	* French (Expert
	* Spanish (Low intermediate)
	* Dutch (Beginner)
* Software and packages:
	* R software(Advanced)
	  * Tidyverse, data.table, ggplot2, EpiNow2, EpiEstim, EpiSewer, xgboost, Rshiny, glmnet, stan, forecast, surveillance, keras, incidence, projections, raster, sf, terra, rgdal, gdistance, seegSDM
	* Microsoft Excel, Office, Word, and Powerpoint (Advanced)
	* SAS and SAS-callable SUDAAN (Intermediate, formerly advanced)
	* VSCode (Intermediate)
	* Python (Intermediate)
	  * •	numpy, matplotlib, transformers, argparse, ollama 
	* SQL (Basic)

Selected publications
======
See the Publications page for a current list of selected publications.
  
Conferences and talks
======
See the Talks page for a current list of conference presentations and invited talks.
  
Professional Organizations
======
* 2014 - 2015
	* Society of Behavioral Medicine (Member)
* 2015 - 2017
	* American Statistical Association (Member)
* 2018 - 2024
	* American Society for Tropical Medicine and Hygiene (Member)
* 2023-2025
	* Society for Epidemiologic Research (Member)

---

Contact me for a copy of my full CV
